name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  find:
    name: Find apps
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.apps.outputs.addons_list }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1

      - name: Find app directories
        id: apps
        uses: home-assistant/actions/helpers/find-addons@master

  lint:
    name: Lint ${{ matrix.path }}
    needs: find
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJSON(needs.find.outputs.apps) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1

      - name: Run Home Assistant app linter
        uses: frenck/action-addon-linter@v2
        with:
          path: ./${{ matrix.path }}

      - name: Test launcher
        run: python3 -m unittest discover -s ./${{ matrix.path }}/tests -v
